# Generated by Django 3.0.5 on 2020-05-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
